image: archlinux/base


stages:
    - formatting
    - builds
    - unit-tests
    - end-to-end-tests


formatting:
    stage: formatting
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S rust diffutils gawk grep --noconfirm
    script:
        - for i in $( du -a ./src/ | awk '{print $2}' | grep -i "[.]rs$" ); do
        - echo $i
        - cp $i temp.txt
        - rustfmt $i
        - cmp $i temp.txt
        - done
    only:
        - branches


builds:
    stage: builds
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel libffi rust --noconfirm
    script:
        - cargo build
    only:
        - branches


unit-tests:
    stage: unit-tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel libffi rust --noconfirm
    script:
        - cargo test
    only:
        - branches


end-to-end-tests:
    stage: end-to-end-tests
    before_script:
        - pacman -Sy --noconfirm
        - pacman -S base-devel libffi rust --noconfirm
        - cargo build --release
        - pacman -S git python python-pip --noconfirm
        - cd end-to-end-tests/
        - pip install -r requirements.txt
    script:
        - behave
    only:
        - branches
