[package]
name = "conventional_commits_next_version"
version = "1.1.0"
description = "A utility to calculate the next Semantic Versioning based upon the Conventional Commits Git commit messages since the last version."
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://gitlab.com/DeveloperC/conventional_commits_next_version"
readme = "README.md"
keywords = ["conventional", "commits", "semantic", "versioning", "git"]
categories = ["command-line-utilities", "development-tools"]


[dependencies]
git2 = "0.13.11"
structopt = "0.3.17"
log = "0.4.11"
pretty_env_logger = "0.4.0"
semver = "0.10.0"
regex = "1.3.9"
lazy_static = "1.4.0"


[dev-dependencies]
rstest = "0.6.4"
