[package]
name = "conventional-commits-next-version"
version = "0.3.0"
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2018"

[lib]
name = "conventional_commits_next_version_lib"
path = "src/lib.rs"

[[bin]]
name = "conventional_commits_next_version"
path = "src/bin.rs"

[dependencies]
git2 = "0.13.5"
structopt = "0.3.14"
log = "0.4.8"
pretty_env_logger = "0.4.0"
semver = "0.9.0"
regex = "1.3.7"
lazy_static = "1.4.0"

[dev-dependencies]
rstest = "0.6.3"
