[package]
name = "conventional_commits_next_version"
version = "1.0.0"
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.13.6"
structopt = "0.3.14"
log = "0.4.8"
pretty_env_logger = "0.4.0"
semver = "0.10.0"
regex = "1.3.9"
lazy_static = "1.4.0"

[dev-dependencies]
rstest = "0.6.3"
