[workspace]

members = [
    "conventional_commits_next_version",
    "conventional_commits_next_version_lib",
]


[patch.crates-io]
conventional_commits_next_version_lib = { path = "conventional_commits_next_version_lib" }


[profile.release]
lto = 'fat'
codegen-units = 1
