[package]
name = "conventional_commits_next_version"
version = "1.1.0"
description = "conventional_commits_next_version is a utility to calculate the next Semantic Versioning 2.0.0 (https://semver.org/spec/v2.0.0.html) based upon the supplied version and the Git commit history in the Conventional Commits v1.0.0 format (https://www.conventionalcommits.org/en/v1.0.0/)."
authors = ["C <DeveloperC@protonmail.com>"]
edition = "2018"
license = "GPL-3.0"
repository = "https://gitlab.com/DeveloperC/conventional_commits_next_version"
readme = "README.md"
keywords = ["conventional", "commits", "semantic", "versioning", "git"]
categories = ["command-line-utilities", "development-tools"]


[dependencies]
git2 = "0.13.8"
structopt = "0.3.15"
log = "0.4.11"
pretty_env_logger = "0.4.0"
semver = "0.10.0"
regex = "1.3.9"
lazy_static = "1.4.0"


[dev-dependencies]
rstest = "0.6.4"
